"""Remove nullable constraints from password_hash

Revision ID: 179e7d4554e9
Revises: e56a777c5110
Create Date: 2025-11-26 18:05:27.639990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179e7d4554e9'
down_revision = 'e56a777c5110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
